---
title: "Explaining restrictions"
format:
  html:
    code-fold: true
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(
  fig.width = 6, fig.height = (6 * 0.618), out.width = "80%",
  fig.align = "center", fig.retina = 3,
  collapse = TRUE
)

options(digits = 3, width = 120, dplyr.summarise.inform = FALSE)
```

```{r}
#| label: libraries-data
#| warning: false
#| message: false

library(tidyverse)
library(tidybayes)
library(modelsummary)
library(marginaleffects)
library(scales)
library(glue)
library(ggtext)
library(patchwork)
library(ggh4x)
library(tinytable)
library(targets)

tar_config_set(
  store = here::here("_targets"),
  script = here::here("_targets.R")
)

tar_load(c(m_restrictions, m_tbl_restrictions))

invisible(list2env(tar_read(graphic_functions), .GlobalEnv))
invisible(list2env(tar_read(diagnostic_functions), .GlobalEnv))
invisible(list2env(tar_read(helper_functions), .GlobalEnv))
invisible(list2env(tar_read(modelsummary_functions), .GlobalEnv))

set_annotation_fonts()
```

# Model details

## Formal model specification

$$
\begin{aligned}
&\ \mathrlap{\textbf{Model of outcome level $i$ across week $t$}} \\
\text{Outcome}_{it_j} \sim&\ \operatorname{Ordered\ logit}(\phi_{it_j}, \alpha_k) \\[0.75em]
&\ \textbf{Distribution parameters} \\
\phi_{it} =&\ \beta_0 + \beta_1\ \text{PanBack (binary)}_{it} + \beta_2\ \text{Derogation in effect}_{it} + \\
&\ \beta_3\ [\text{PanBack (binary)}_{it} \times \text{Derogation in effect}_{it}] + \\
&\ \beta_4\ \text{New cases}_{it}\ + \beta_5\ \text{Cumulative cases}_{it}\ + \\
&\ \beta_6\ \text{New deaths}_{it}\ + \beta_7\ \text{Cumulative deaths}_{it}\ + \\
&\ \beta_8\ \text{Rule of law index}_{it}\ + \beta_9\ \text{Week number}_{it} \\[0.75em]
&\ \textbf{Priors} \\
\beta_{0 \dots 9} \sim&\ \operatorname{Student\ t}(\nu = 1, \mu = 0, \sigma = 3) \\
\alpha_k \sim&\ \mathcal{N}(0, 1)
\end{aligned}
$$

## Priors

```{r}
#| label: figure-prior
#| fig-cap: "Density plot of prior distribution for model parameters"
#| fig-width: 3.5
#| fig-height: 2.5
#| out-width: "50%"

ggplot() +
  stat_function(
    geom = "area",
    fun = ~extraDistr::dlst(., df = 1, mu = 0, sigma = 3),
    fill = clrs[2]
  ) +
  xlim(c(-20, 20)) +
  labs(x = "βs") +
  facet_wrap(vars("β: Student t(ν = 1, µ = 0, σ = 3)")) +
  theme_pandem(prior = TRUE)
```

## Simplified R code

```r
brm(
  bf(outcome ~ derogation_ineffect*panbackdichot +
      new_cases_z + cumulative_cases_z +
      new_deaths_z + cumulative_deaths_z +
      v2x_rule + year_week_num),
  family = cumulative(),
  prior = c(
    prior(student_t(1, 0, 3), class = Intercept),
    prior(student_t(1, 0, 3), class = b)),
  ...
)
```

## Model evaluation

```{r}
params_to_show <- c("b_Intercept[1]", "b_derogation_ineffect", "b_panbackdichot", "b_v2x_rule")
```

::: {.panel-tabset}

### Restricted movement

```{r}
plot_trace(m_restrictions$m_restrict_movement, params_to_show)
```

```{r}
plot_trank(m_restrictions$m_restrict_movement, params_to_show)
```

```{r}
plot_pp(m_restrictions$m_restrict_movement)
```

### Close public transit

```{r}
plot_trace(m_restrictions$m_restrict_pubtrans, params_to_show)
```

```{r}
plot_trank(m_restrictions$m_restrict_pubtrans, params_to_show)
```

```{r}
plot_pp(m_restrictions$m_restrict_pubtrans)
```

### Stay at home

```{r}
plot_trace(m_restrictions$m_restrict_stayhome, params_to_show)
```

```{r}
plot_trank(m_restrictions$m_restrict_stayhome, params_to_show)
```

```{r}
plot_pp(m_restrictions$m_restrict_stayhome)
```

:::


# Results

## Predictions

```{r}
#| label: calc-preds-restrictions

preds_movement <- calc_preds(m_restrictions$m_restrict_movement)
preds_movement_details <- calc_preds_details(preds_movement)
diffs_movement <- calc_preds_diffs(preds_movement)
diffs_movement_details <- calc_preds_diffs_details(diffs_movement)

preds_pubtrans <- calc_preds(m_restrictions$m_restrict_pubtrans)
preds_pubtrans_details <- calc_preds_details(preds_pubtrans)
diffs_pubtrans <- calc_preds_diffs(preds_pubtrans)
diffs_pubtrans_details <- calc_preds_diffs_details(diffs_pubtrans)

preds_stayhome <- calc_preds(m_restrictions$m_restrict_stayhome)
preds_stayhome_details <- calc_preds_details(preds_stayhome)
diffs_stayhome <- calc_preds_diffs(preds_stayhome)
diffs_stayhome_details <- calc_preds_diffs_details(diffs_stayhome)
```

```{r}
#| label: figure-restrictions-preds
#| fig-cap: Predicted probabilities of imposing emergency policies across states with low and high risks of democratic backsliding and derogation status
#| fig-width: 6.5
#| fig-height: 8.5
#| out-width: 100%

p1 <- ggplot(preds_movement, aes(x = .draw, y = .epred)) +
  geom_area(aes(fill = .category), position = position_stack()) +
  geom_label(
    data = calc_fuzzy_labs(preds_movement_details, filter_small = FALSE),
    aes(x = x, y = y, label = prob_ci_nice, hjust = hjust),
    fill = scales::alpha("white", 0.4), label.size = 0,
    fontface = "bold", size = 8, size.unit = "pt"
  ) +
  scale_x_continuous(breaks = NULL, expand = c(0, 0)) +
  scale_y_continuous(labels = label_percent(), expand = c(0, 0)) +
  scale_fill_manual(values = clrs[c(7, 4, 2)]) +
  labs(
    x = NULL, y = "Cumulative\nprobabilities",
    fill = "Internal movement measures", tag = "A"
  ) +
  facet_nested_wrap(
    vars(panbackdichot, derogation_ineffect),
    strip = nested_settings,
    nrow = 1
  ) +
  theme_pandem() +
  theme_fuzzy_bar

p2 <- ggplot(preds_pubtrans, aes(x = .draw, y = .epred)) +
  geom_area(aes(fill = .category), position = position_stack()) +
  geom_label(
    data = calc_fuzzy_labs(preds_pubtrans_details, filter_small = FALSE),
    aes(x = x, y = y, label = prob_ci_nice, hjust = hjust),
    fill = scales::alpha("white", 0.4), label.size = 0,
    fontface = "bold", size = 8, size.unit = "pt"
  ) +
  scale_x_continuous(breaks = NULL, expand = c(0, 0)) +
  scale_y_continuous(labels = label_percent(), expand = c(0, 0)) +
  scale_fill_manual(values = clrs[c(7, 4, 2)]) +
  labs(
    x = NULL, y = "Cumulative\nprobabilities",
    fill = "Public transportation measures", tag = "B"
  ) +
  facet_nested_wrap(
    vars(panbackdichot, derogation_ineffect),
    strip = nested_settings,
    nrow = 1
  ) +
  theme_pandem() +
  theme_fuzzy_bar

p3 <- ggplot(preds_stayhome, aes(x = .draw, y = .epred)) +
  geom_area(aes(fill = .category), position = position_stack()) +
  geom_label(
    data = calc_fuzzy_labs(preds_stayhome_details, filter_small = TRUE),
    aes(x = x, y = y, label = prob_ci_nice, hjust = hjust),
    fill = scales::alpha("white", 0.4), label.size = 0,
    fontface = "bold", size = 8, size.unit = "pt"
  ) +
  scale_x_continuous(breaks = NULL, expand = c(0, 0)) +
  scale_y_continuous(labels = label_percent(), expand = c(0, 0)) +
  scale_fill_manual(values = clrs[c(7, 4, 2, 1)], guide = guide_legend(nrow = 2)) +
  labs(
    x = NULL, y = "Cumulative\nprobabilities",
    fill = "Stay at home measures", tag = "C"
  ) +
  facet_nested_wrap(
    vars(panbackdichot, derogation_ineffect),
    strip = nested_settings,
    nrow = 1
  ) +
  theme_pandem() +
  theme_fuzzy_bar

(p1 / line_divider / p2 / line_divider / p3) +
  plot_layout(heights = c(0.31, 0.035, 0.31, 0.035, 0.31)) +
  plot_annotation(
    caption = str_wrap(
      glue(
        "The vertical slices of the bars depict 500 posterior samples;",
        "the fuzziness represents the uncertainty in category boundaries.",
        "95% credible intervals are shown as ranges in each category",
        .sep = " "
      ),
      width = 100
    ),
    theme = theme(
      plot.caption = element_text(
        margin = margin(t = 10), size = rel(0.7),
        family = "Noto Sans", face = "plain"
      )
    )
  )
```

## Complete table of results

```{r}
#| label: table-results-full-restrictions
#| tbl-cap: "Complete results from models showing relationship between derogations and COVID-19 restrictions"

notes <- paste(
  "Note: Estimates are median posterior log odds from ordered logistic regression models;",
  "95% credible intervals (highest density posterior interval, or HDPI) in brackets."
)

m_tbl_restrictions |>
  set_names(c("Restricted movement", "Close public transit", "Stay at home")) |>
  modelsummary(
    estimate = "{estimate}",
    statistic = "[{conf.low}, {conf.high}]",
    coef_map = coef_map,
    gof_map = gof_map,
    output = "tinytable",
    fmt = fmt_significant(2),
    notes = notes,
    width = c(0.3, rep(0.23, 3))
  ) |>
  style_tt(i = seq(1, 23, 2), j = 1, rowspan = 2, alignv = "t") |>
  style_tt(
    bootstrap_class = "table table-sm"
  )
```

## Contrasts

```{r}
#| label: figure-restriction-diffs
#| fig-cap: Contrasts in predicted probabilities of implementing COVID restrictions across states with low and high risks of democratic backsliding and derogation status
#| fig-width: 9.5
#| fig-height: 8.75
#| out-width: 100%
#| lightbox: true

p1 <- diffs_movement |>
  ggplot(aes(x = .epred, y = fct_rev(.category), color = .category)) +
  geom_vline(xintercept = 0, linewidth = 0.25, linetype = "21") +
  stat_pointinterval() +
  facet_nested_wrap(vars(panbackdichot, derogation_ineffect), strip = nested_settings_diffs) +
  scale_x_continuous(labels = label_pp) +
  scale_color_manual(values = clrs[c(7, 4, 2)], guide = "none") +
  labs(
    x = NULL, y = NULL,
    title = "Internal movement measures", tag = "A"
  ) +
  theme_pandem() +
  theme_diffs

p2 <- diffs_pubtrans |>
  ggplot(aes(x = .epred, y = fct_rev(.category), color = .category)) +
  geom_vline(xintercept = 0, linewidth = 0.25, linetype = "21") +
  stat_pointinterval() +
  facet_nested_wrap(vars(panbackdichot, derogation_ineffect), strip = nested_settings_diffs) +
  scale_x_continuous(labels = label_pp) +
  scale_color_manual(values = clrs[c(7, 4, 2)], guide = "none") +
  labs(
    x = NULL, y = NULL,
    title = "Public transportation measures", tag = "B"
  ) +
  theme_pandem() +
  theme_diffs

p3 <- diffs_stayhome |>
  ggplot(aes(x = .epred, y = fct_rev(.category), color = .category)) +
  geom_vline(xintercept = 0, linewidth = 0.25, linetype = "21") +
  stat_pointinterval() +
  facet_nested_wrap(vars(panbackdichot, derogation_ineffect), strip = nested_settings_diffs) +
  scale_x_continuous(labels = label_pp) +
  scale_color_manual(values = clrs[c(7, 4, 2, 1)], guide = "none") +
  labs(
    x = NULL, y = NULL,
    title = "Stay at home measures", tag = "C"
  ) +
  theme_pandem() +
  theme_diffs

(p1 / line_divider / p2 / line_divider / p3) +
  plot_layout(heights = c(0.295, 0.035, 0.295, 0.035, 0.34)) +
  plot_annotation(
    caption = str_wrap(
      glue(
        "Point shows posterior median;", "
        thick lines show 80% credible interval;",
        "thin black lines show 95% credible interval",
        .sep = " "
      ),
      width = 150
    ),
    theme = theme(
      plot.caption = element_text(
        margin = margin(t = 10), size = rel(0.7),
        family = "Noto Sans", face = "plain"
      )
    )
  )
```

::: {.panel-tabset}
### Internal movement

```{r}
make_diffs_tbl(diffs_movement)
```

### Public transportation

```{r}
make_diffs_tbl(diffs_pubtrans)
```

### Stay at home

```{r}
make_diffs_tbl(diffs_stayhome)
```
:::
