---
title: "Hypotheses"
format:
  html:
    code-fold: true
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(
  # echo = FALSE, include = FALSE, warning = FALSE, message = FALSE,
  fig.width = 6, fig.height = (6 * 0.618), out.width = "80%",
  fig.align = "center", fig.retina = 3,
  collapse = TRUE
)

options(digits = 3, width = 120, dplyr.summarise.inform = FALSE)
```

```{r}
#| label: libraries-data
#| warning: false
#| message: false

library(tidyverse)
library(tinytable)
```

```{r}
#| label: table-expectations
#| tbl-cap: "Expectations about state transparency and practices during COVID-19"

tbl <- tribble(
  ~` `, ~Derogation, ~`No derogation`,
  "Backsliding", "Transparency about restrictions and violations", "Low/no transparency about restrictions and violations",
  "", "*Motivations*: Legitimation and reputation concerns", "*Motivations*: Leader not concerned about reputation backlash",
  "No backsliding", "High transparency about potential restrictions and violations", "Limited/no transparency about restrictions and violations",
  "", "*Motivations*: Strong rule of law and valuation of international regime", "*Motivations*: Limited concern about reputation backlash and limited valuation of international regime"
)

tbl |>
  tt(width = c(1, 2, 2)) |>
  format_tt(j = 2:3, markdown = TRUE) |>
  style_tt(j = 1:3, align = "lll") |>
  style_tt(i = seq(1, 5, by = 2), j = 1, bold = TRUE, rowspan = 2, alignv = "t") |>
  style_tt(
    bootstrap_class = "table table-sm"
  )
```

- **H~1~**: States experiencing democratic backsliding will be more likely to issue derogations.
- **H~2~**: States experiencing democratic backsliding will be more likely to abuse human rights.
- **H~3~**: States experiencing democratic backsliding that also issue derogations will be less likely to abuse human rights than states that only backslide.
